name: sparco_pay
description: A Sparco payment gateway client for dart
version: 1.0.0
repository: https://github.com/dhmgroup/sparco_dart

environment:
  sdk: '>=2.19.0-444.0.dev <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
